apiVersion: apps/v1
kind: Deployment
metadata:
  name: c9-7-deploy
spec:
  replicas: 3
  minReadySeconds: 10
  selector:
    matchLabels:
      app: kubia
  template:
    metadata:
      name: kubia
      labels:
        app: kubia
    spec:
      containers:
        - name: c9-7-deploy
          image: luksa/kubia:v1