apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name : hello
spec:
  storageClassName: "longhorn"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  selector:
    matchLabels:
      app: prometheus