apiVersion: v1
kind: Pod
metadata:
  name: liveness-test-pod
spec:
  containers:
    - image: ojt90902/ash:latest
      name: ash
      livenessProbe:
        initialDelaySeconds: 15 # 초기에는 파드가 바로 대응할 준비가 안됨.
        successThreshold: 1 # 한번만 성공해도 성공.
        failureThreshold: 5 # 다섯 번 실패해야 실패로 인정함.
        timeoutSeconds: 10 # 이 시간동안 응답오지 않으면 실패로 봄.
        periodSeconds: 1
        httpGet:
          port: 8080
          path: /health-check
      ports:
        - containerPort: 8080
          protocol: TCP