apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: k8s-in-action
spec:
  containers:
    - name: k8s-in-action-5-1-1
      image: ojt90902/ash:latest
      ports:
        - containerPort: 80
          name: http

