apiVersion: v1
kind: Pod
metadata:
  name: ash-node-1-1
  labels:
    nodeselector: "1"
spec:
  nodeSelector:
    NODE: "1"
  containers:
  - image: ojt90902/ash:latest
    name: ash
    livenessProbe:
      timeoutSeconds:
      initialDelaySeconds:
      failureThreshold:
      periodSeconds:
      successThreshold:
      terminationGracePeriodSeconds:
      httpGet:
        port:

    ports:
    - containerPort: 8080
      protocol: TCP