apiVersion: v1
kind: Pod
metadata:
  name: ash-node-2
  labels:
    nodeselector: "1"
spec:
  nodeSelector:
    NODE: "1"
  containers:
  - image: ojt90902/ash:latest
    name: ash
    ports:
    - containerPort: 8080
      protocol: TCP