apiVersion: v1
kind: Pod
metadata:
  name: ubuntu-dns
  labels:
    app: k8s-in-action
spec:
  containers:
    - name: dns
      image: ojt90902/ubuntu:latest
      ports:
        - containerPort: 80
          name: http

