apiVersion: v1
kind: Pod
metadata:
  name: c8-1
spec:
  containers:
    - name: c8-1
      image: ojt90902/all:latest
      imagePullPolicy: Always
      command: ["sleep", "999d"]
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: SERVICE_ACCOUNT
          valueFrom:
            fieldRef:
              fieldPath: spec.serviceAccountName
        - name: CONTAINER_CPU_REQUEST_MILLICORES
          valueFrom:
            resourceFieldRef:
              resource: request.cpu
              divisor: 1m
        - name: CONTAINER_MEMORY_REQUEST_KIBIBYTES
          valueFrom:
            resourceFieldRef:
              resource: request.memory
              divisor: 1Ki