apiVersion: v1
kind: Pod
metadata:
  name: c7-16
spec:
  containers:
    - name: c7-16-nginx
      image: nginx:alpine
      volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: config
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: fortune-config
        items:
          - path: gzip.conf
            key: my-nginx-config.conf
