apiVersion: apps/v1
kind: Deployment
metadata:
  name: c16-13-back
spec:
  replicas: 1
  selector:
    matchLabels:
      app: back-13
  template:
    metadata:
      name: c16-13-back
      labels:
        app: back-13
    spec:
      containers:
        - name: back
          image: busybox
          command: [ "sleep", "99999" ]
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: sha-test
                    operator: Exists