apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: c6-14
provisioner: driver.longhorn.io
parameters:
  numberOfReplicas: "3"
  staleReplicaTimeout: "30"
  fromBackup: ""
  fsType: "ext4"
  dataLocality: "disabled"