apiVersion: v1
kind: Pod
metadata:
  name: c7-24-nginx
spec:
  containers:
    - name: html-generator
      image: ojt90902/fortune:env
      env:
        - name: INTERVAL
          valueFrom:
            configMapKeyRef:
              key: sleep-interval
              name: fortune-config
      volumeMounts:
        - mountPath:  /var/htdocs
          name: html

    - name: web-server
      image: nginx:alpine
      volumeMounts:
        - mountPath:  /usr/share/nginx/html
          name: html
          readOnly: true
        - mountPath: /etc/nginx/conf.d
          name: config
          readOnly: true
        # Secret으로 볼륨 마운트
        - name: certs
          mountPath: /etc/nginx/certs
          readOnly: true
      ports:
        - containerPort: 80
          name: http
        - containerPort: 443
          name: https
  volumes:
    - name: html
      emptyDir: {}
    - name: config
      configMap:
        name: fortune-config
        items:
          - key: my-nginx-config.conf
            path: https.conf
    - name: certs
      secret:
        secretName: fortune-https
