version: '3.8'
services:
  db:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: peoplein
      MYSQL_DATABASE: moiming
  cli:
    image: ojt90902/ubuntu-all:latest
    entrypoint: ["sleep", "1d"]
    depends_on:
      - db
