apiVersion: v1
kind: Pod
metadata:
  name: c7-17
spec:
  containers:
    - name: c7-17-nginx
      image: nginx:alpine
      volumeMounts:
        - mountPath: /etc/nginx/conf.d/default.conf1
          name: config
          subPath: gzip.conf
          readOnly: true
  volumes:
    - name: config
      configMap:
        name: fortune-config
        items:
          - path: gzip.conf
            key: my-nginx-config.conf
