apiVersion: apps/v1
kind: Deployment
metadata:
  name: c9-11-deploy
spec:
  replicas: 10
  minReadySeconds: 10
  progressDeadlineSeconds: 11
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
  selector:
    matchLabels:
      app: c9-11-deploy-kubia
  template:
    metadata:
      name: c9-11-deploy-kubia
      labels:
        app: c9-11-deploy-kubia
    spec:
      containers:
        - name: c9-11-deploy
          image: luksa/kubia:v1
          readinessProbe:
            periodSeconds: 1
            httpGet:
              port: 8080
              path: /
