# 하나의 서비스는 다중 포트를 지원할 수 있음.
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    service: hello
spec:
   sessionAffinity: ClientIP
   selector:
     app: k8s-in-action
   ports:
     - port: 80
       targetPort: 8080
       name: http # 서비스 포트 이름 설정
     - port: 443
       targetPort: 8443
       name: https # 서비스 포트 이름 설정
