# 노드포트 서비스 선언
apiVersion: v1
kind: Service
metadata:
  name: hello-node-port
spec:
  type: NodePort # 서비스 타입 선택
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30200 # 선언하지 않으면 알아서 생성됨.
  selector:
    app: from-node