apiVersion: apps/v1
kind: Deployment
metadata:
  name: c16-9
spec:
  replicas: 10
  selector:
    matchLabels:
      app: c16-9
  template:
    metadata:
      labels:
        app: c16-9
    spec:
      affinity:
        nodeAffinity:
      containers:
        - name: c16-9
          image: busybox
          command: ["sleep", "99999"]