apiVersion: batch/v1
kind: CronJob
metadata:
  name: c4-14-batch-job-every-fifteen-minutes
spec:
  schedule: "0,15,30,45 * * * *"
  # Job Template1
  jobTemplate:
    # Pod Template
    spec:
      template:
        metadata:
          labels:
            app: periodic-batch-job
        spec:
          containers:
            - name: main
              image: luksa/batch-job