apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: c-10-4-kubia
spec:
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 10%
  selector:
    matchLabels:
      app: c-10-4-kubia
  serviceName: c-10-4-kubia
  template:
    metadata:
      name: c-10-4-kubia
      labels:
        app: c-10-4-kubia
    spec:
      containers:
        - name: kubia
          image: luksa/kubia-pet
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - mountPath: /var/data
              name: data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: longhorn
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Mi