apiVersion: v1
kind: ResourceQuota
metadata:
  name: c14-15
spec:
  hard:
    request.storage: 500Gi # 요청 가능한 스토리지의 전체 용량
    ssd.storageclass.storage.k8s.io/requests.storage: 300Gi # SSD 스토리지 클래스에서 요청 가능한 스토리지 용량
    standard.storageclass.storage.k8s.io/requests.storage: 1Ti # HDD 스토리지 클래스에서 요청 가능한 스토리지 용량