# 파드 포트에 이름 붙여주기
apiVersion: v1
kind: Pod
metadata:
  name: hello-pod
  labels:
    app: k8s-in-action
spec:
  dnsPolicy:
  containers:
    - name: k8s-in-action-5-1-1
      image: ojt90902/ash:latest
      ports:
        - containerPort: 80
          name: http-pod
        - containerPort: 8443
          name: https-pod

