# 파드의 파드 이름을 서비스에서 사용할 수 있음.
# 파드의 포트번호는 파드의 포트 이름으로 캡슐화 됨.
apiVersion: v1
kind: Service
metadata:
  name: hello-service
  labels:
    service: hello
spec:
   sessionAffinity: ClientIP
   selector:
     app: k8s-in-action
   ports:
     - port: 80
       targetPort: http-pod # 파드의 포트 이름을 사용함.
       name: http
     - port: 443
       targetPort: http-pods # 파드의 포트 이름을 사용함.
       name: https
