apiVersion: v1
kind: Pod
metadata:
  name: ash1
  labels:
    app: hello1
    phase: beta
spec:
  containers:
  - image: ojt90902/ash:latest
    name: ash
    ports:
    - containerPort: 8080
      protocol: TCP