# 로드밸런서 선언
apiVersion: v1
kind: Service
metadata:
  name: hello-loadbalncer
spec:
  type: LoadBalancer # 로드밸런서. 쿠버네티스 클러스터에서 로드밸런서 지원하면 얻을 수 있음.
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30200 # 선언하지 않으면 알아서 생성됨.
  selector:
    app: from-node