apiVersion: v1
kind: Pod
metadata:
  name: c14-13-pod
spec:
  containers:
    - name: main
      image: busybox
      command: ["dd", "if=/dev/zero", "of=/dev/null"]
      resources:
        requests:
          cpu: 20m
          memory: 20Mi
        limits:
          cpu: 20m
          memory: 20Mi